CC = gcc
CFLAGS = -I./inc -g -O2

# We must manually list every single C file in the project.
# If you add a new file 'div.c', you MUST edit this list manually.
# List of all source files i.e. .c files
SRCS = main.c \
       src/src1/add.c \
       src/src2/sub.c \
       src/src3/mul.c \
       src/src4/div.c

# We must manually list every single Object file we expect to generate.
# List of all object files i.e. .o files
OBJS = main.o \
       src/src1/add.o \
       src/src2/sub.o \
       src/src3/mul.o \
       src/src4/div.o

# The Target Rule
# Here our daemon depends on list of object files.
Daemon: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o Daemon
	@echo "App Binary Generated"

# The Pattern Rule
# (Note: This is technically a Rule, not a Function, so we keep it.
# It tells Make how to compile any .c to .o)
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) Daemon