# target: dependancies for generating
# <tab> command to generate the target
# <tab> echo "------"

target: main.c
	gcc main.c -o main
	@cho "Application generated"

# Without @
# gcc main.c -o main
# echo "Application generated"
# Application generated

# With @
# gcc main.c -o main
# Application generated